apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: mariadb
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mariadb
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: mariadb
   spec:
     containers:
     - image: mariadb
       imagePullPolicy: Always
       name: mariadb
       volumeMounts:        
       - mountPath: /var/lib/mysql
         name: pvc-evs-example
       env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: mariadb-secret
                  key: root_password
          - name: MYSQL_DATABASE
            valueFrom:
               secretKeyRef:
                  name: mariadb-secret
                  key: mysql_database
          - name: MYSQL_DATABASE
            value: fedemo
          - name: MYSQL_USER
            value: fedemo
          - name: MYSQL_PASSWORD
            value: fedemo
       resources: 
           requests:
              cpu: 2
              memory: 2048Mi
     volumes:
     - name: pvc-evs-example
       persistentVolumeClaim:
          claimName: cce-evs-ernest-mariadb 
     imagePullSecrets:
       - name: default-secret
