apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: mariadb
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mariadb
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: mariadb
   spec:
     containers:
     - image: mariadb
       imagePullPolicy: Always
       name: mariadb
       env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: mariadb-secret
                  key: root_password
          - name: MYSQL_DATABASE
            valueFrom:
               secretKeyRef:
                  name: mariadb-secret
                  key: mysql_database
       resources: 
           requests:
              cpu: 2
              memory: 2048Mi
     imagePullSecrets:
       - name: default-secret
