apiVersion: v1
kind: Service
metadata:
 annotations:
   kubernetes.io/elb.class: union
   kubernetes.io/elb.id: 053ba177-982f-47c9-a4be-75cb8c499bfa 
 labels:
   app: nodered
 name: nodered
spec:
 loadBalancerIP: 90.84.195.132 # IP address of the an ELB service in a public 
 ports:
 - name: service0
   port: 1880 # Cluster virtual IP address access port, which has 
   protocol: TCP
   targetPort: 1880 # Container port set on the CCE console.
 selector:
   app: nodered
 type: LoadBalancer # The EIP must be based on an NodePort service.
