apiVersion: v1
kind: Service
metadata:
 labels:
   app: adminer-cic
 name: adminer-cic-nodeport
spec:
 ports:
 - name: webadminer
   nodePort: 30080
   port: 8080  
   protocol: TCP
   targetPort: 8080
 selector:
   app: adminer-cic
 type: NodePort 
