apiVersion: v1
kind: Service
metadata:
 labels:
   app: mariadb-cic
 name: mariadb-cic-nodeport
spec:
 ports:
 - name: mariadb
   nodePort: 30306
   port: 3306  
   protocol: TCP
   targetPort: 3306
 selector:
   app: mariadb-cic
 type: NodePort 