apiVersion: v1
kind: Service
metadata:
 labels:
   app: nodered-cic
 name: nodered-cic-nodeport
spec:
 ports:
 - name: nodered
   nodePort: 30880
   port: 1880  
   protocol: TCP
   targetPort: 1880
 selector:
   app: nodered-cic
 type: NodePort 