apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nodered-cic
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nodered-cic
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: nodered-cic
   spec:
     containers:
     - image: nodered/node-red-docker
       imagePullPolicy: Always
       name: nodered
       resources: 
           requests:
              cpu: 2
              memory: 4096Mi
     imagePullSecrets:
       - name: default-secret
